---
# tasks for omero-web

- name: omero-web | import web-dependency
  ansible.builtin.import_tasks: web-dependencies.yml

- name: omero-web | import web-install-py3
  ansible.builtin.import_tasks: web-install-py3.yml

- name: omero-web | import web-systemd.yml
  ansible.builtin.import_tasks: web-systemd.yml
  when: omero_web_systemd_setup

- name: omero-web | import web-nginx.yml
  ansible.builtin.import_tasks: web-nginx.yml
  when: omero_web_setup_nginx
