---
# tasks for omero-web

- include: web-user.yml

- include: web-dependencies.yml

- include: web-install.yml

- include: web-systemd.yml
  when: omero_web_systemd_setup

- include: web-nginx.yml
  when: omero_web_setup_nginx
