---
# NOTE: The Ansible variable `ansible_selinux.status == "enabled"` should
# autodetect SELinux, but may give a misleading result if a dependency is
# missing: https://github.com/ansible/ansible/issues/16612
# so use getenforce instead

# Always run including in check mode
- name: omero web | check selinux exists
  stat:
    path: /usr/sbin/getenforce
  register: selinux_getenforce_st
  check_mode: no

- name: selinux | check  selinux enabled
  become: yes
  command: /usr/sbin/getenforce
  register: selinux_getenforce
  check_mode: no
  changed_when: False
  when: selinux_getenforce_st.stat.exists

- name: omero web | set selinux variable
  set_fact:
    selinux_enabled: "{{ selinux_getenforce_st.stat.exists and selinux_getenforce.stdout != 'Disabled' }}"

- name: selinux | check enabled
  become: yes
  command: /usr/sbin/restorecon -R -v {{ omero_web_basedir }}/OMERO.web
  check_mode: no
  when: selinux_enabled

