---
# Curl isn't installed, needed for tests

- name: Prepare
  hosts: all

  tasks:
    - name: Install packages
      become: true
      apt:
        name:
          - curl
          - gnupg
          - ca-certificates
          - python
          - sudo
          - bash
        state: present
